services:
  db:
    image: mysql:8.0.40-debian
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      LANG: C.UTF-8
    volumes:
      - ./Create:/docker-entrypoint-initdb.d/